sudo: required
dist: trusty
language: generic
arch:
  - amd64
  - ppc64le
before_install:
   - sudo apt-get update
   - sudo apt-get install -y --no-install-recommends moreutils dblatex asciidoc texlive-lang-german calibre calibre-bin python-sip epubcheck build-essential debhelper xmlto fakeroot

script:
   - make -j4 verbose
   - make test
   - dpkg-buildpackage -j4 -us -uc

#after_failure:
#   - sudo apt-get install libxml2-utils
#   - make xmllint

notifications:
  irc: irc.lugs.ch#kivamon
